#!/bin/sh
#
# Input JSON from STDIN
# {
#   "source": {
#     "url": "https://download.opensuse.org",
#     "regexp": "file-(.*).ext"
#   },
#   "version": { "ref": "61cebf" }
# }

set -e
IFS=" "

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > $payload <&0

parse_source_config
parse_param_config

DESTINATION_DIR=$1


if [ -z "$VERSION" ] || [ "$VERSION" == "latest" ]; then
  get_listing
  parse_versions
  VERSION=$(echo $FOUND_VERSIONS | sort -r | head -1)
fi
TEMPDEST=$(mktemp -d /tmp/transfer-in.XXXXXX)
cd $TEMPDEST
FILE=$(echo "$REGEXP" | sed -e "s/(.*)/$VERSION/")
lftpget -c "$URL/$FILE"

if [ "$TAR" == "false"]; then
  cp * $DESTINATION_DIR
else
  tar -xf * -C $DESTINATION_DIR
fi

cd $DESTINATION_DIR

# The script must emit the fetched version, and may emit metadata as a list of key-value pairs. This data is intended for public consumption and will make it upstream, intended to be shown on the build's page.
cat >&3 <<EOF
{
  "version": { "ref": "$VERSION" },
  "metadata": [
    { "name": "comment", "value": "$FILE" }
  ]
}
EOF
